### PR TITLE
Fix issue #356: Which is sometimes incorrectly flagged

### PR DESCRIPTION
**Pull request by jhradilek**
Fixes issue #356.

### CODE REVIEW

**Review by aireilly — COMMENTED** [review]
LGTM, this is a great addition to the rules.

**Comment by aireilly** [comment]
One small issue: in Your PR, if you add a line which _does_ have an error above your valid "which" examples, Vale highlights an incorrect line as having an error. This is fixed by adding `scope: sentence` to `TermsSuggestions.yml`. I am not sure whether this is a bug or limitation in Vale tbh. WDYT @jhradilek?

image

**Comment by jhradilek** [comment]
Hi @aireilly, this is a very good observation, I should have caught it: I briefly noticed some odd behavior while fine tuning the regular expression (missing lines in the `testinvalid.adoc`) but failed to recognize it. I will look closer in the evening, but I am not sure why this particular regular expression would behave differently so I wonder if this problem exists for other styles that extend substitution like `SimpleWords.yml`.

**Comment by aireilly** [comment]
I think adding `scope: sentence` to this PR would allow us to merge. WDYT @jhradilek?

**Comment by aireilly** [comment]
Ah I think the issue above is caused by how Asiidoc is rendered into HTML for Vale to parse. AsciiDoc uses carriage return + blank line for paragraphs. Vale runs on the generated HTML. Carriage returns on their own do not equate to sentences. So the regex sees one long sentence in the HTML output. Background: https://writetheasciidocs.netlify.app/ventilated-prose

**Comment by aireilly** [comment]
Closing this as addressed in https://github.com/redhat-documentation/vale-at-red-hat/pull/366

**Comment by aireilly** [comment]
See https://github.com/errata-ai/vale/issues/674

**Pull request closed without merging**
