### PR TITLE
Replace the :_content-type: variable with the :_mod-docs-content-type: variable

### PR DESCRIPTION
**Pull request by rolfedh**
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/679
We won't merge this PR until we get the go-ahead to do so from @kalexand-rh.

### CODE REVIEW

**Comment by rohennes** [comment]
This looks good @rolfedh but as mentioned on Slack, we should wait until OCP moves to the new variable naming convention. I believe that will happen in the next few weeks.

**Comment by rolfedh** [comment]
@kalexand-rh would you review and approve, too?

**Comment by rolfedh** [comment]
We won't merge this PR until we get the go-ahead to do so from @kalexand-rh.

**Comment by kalexand-rh** [comment]
This looks good to me! I've updated the maintained OCP branches [here](https://github.com/openshift/openshift-docs/pull/67071), so this change should be good to incorporate.

**Review by aireilly — APPROVED** [review]
lgtm

**Pull request merged**
