### PR TITLE
Warn against duplicate Vale plugin for Visual Studio Code 

### LINKED ISSUE #725: [BUG] Duplicate Vale plugin for Visual Studio Code
**Describe the bug**

There are 2 plugins on the Visual Studio Code marketplace for Vale. One old version and one newer version. This is confusing for new users of Vale because the old version has about 5000 downloads and the new version only has less than 200. Combined with the less official sounding name of the new version (Vale VSCode vs. Vale) and the fact that the wrong version is the top result, it's not easy to tell which version is the correct one to use at first glance. The correct version to use is the newer 0.18 version.

**To Reproduce**

1. Open Visual Studio Code
2. Search for `vale` in the **Extensions** tab
3. Two competing versions of the Vale extension appear in the search results. The wrong version is the top result, leading to additional confusion about which version to install.

**Expected behavior**

There should only be one Vale plugin available in the search results (the newer version).

**Additional context**

Screenshot 2024-02-28 at 15 59 38
Screenshot 2024-02-28 at 15 59 59

### PR DESCRIPTION
**Pull request by rolfedh**
Fixes #725

### CODE REVIEW

**Review by oafischer — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by aireilly** [comment]
Can you rebase and push again please Rolfe. This should clear the errors.

**Comment by rolfedh** [comment]
> Can you rebase and push again please Rolfe. This should clear the errors.

Thanks for fixing that issue, @aireilly! Good to go now.

**Review by aireilly — APPROVED** [review]
/lgtm

**Pull request merged**
