### PR TITLE
vCentre datacenter is an accepted term in OCP's VMWare implementation

### PR DESCRIPTION
**Pull request by rohennes**
https://docs.openshift.com/container-platform/4.16/installing/installing_vsphere/ipi/ipi-vsphere-installation-reqs.html#installation-vsphere-installer-infra-requirements_ipi-vsphere-installation-reqs

vCenter datacenter is valid here

### CODE REVIEW

**Comment by rohennes** [comment]
@jeana-redhat - does this fix the issue that you [mentioned](https://redhat-internal.slack.com/archives/C0218RXJK5E/p1719424444678899?thread_ts=1719423520.645449&cid=C0218RXJK5E) in passing?

**Comment by jeana-redhat** [comment]
> @jeana-redhat - does this fix the issue that you [mentioned](https://redhat-internal.slack.com/archives/C0218RXJK5E/p1719424444678899?thread_ts=1719423520.645449&cid=C0218RXJK5E) in passing?

well, upon more digging, I think maybe the sources we have gotten "datacenter" from in the past are either erroneous or outdated. [Current VMware docs](https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-vcenter-esxi-management/GUID-7FDFBDBE-F8AC-4D00-AE5E-3F14D7472FAF.html) seems to have two words, lowercase ("data center") :upside_down_face:

**Review by aireilly — APPROVED** [review]
/lgtm

**Comment by aireilly** [comment]
Argh. Merged this and didn't spot @jeana-redhat's comment. Is there more work we need to do here? Can you follow up with another PR if so. Sorry.

**Comment by jeana-redhat** [comment]
> Argh. Merged this and didn't spot @jeana-redhat's comment. Is there more work we need to do here? Can you follow up with another PR if so. Sorry.

probably just a revert

**Pull request merged**
