### PR TITLE
Create a Localization rule set

### PR DESCRIPTION
**Pull request by rolfedh**
Fixes [Create a localization rule to highlight common errors that cause trouble for translators #515](https://github.com/redhat-documentation/vale-at-red-hat/issues/515)

### CODE REVIEW

**Comment by rolfedh** [comment]
@[cguttman@redhat.com](mailto:cguttman@redhat.com)

**Comment by aireilly** [comment]
Layout looks fine to me.

**Review by aireilly — COMMENTED** [review]
Wonder would a metric rule be useful: https://vale.sh/docs/topics/styles/#metric

**Comment by aireilly** [comment]
To progress this new Localization rule set work, and to minimize confusion for VRH contributors, I propose the bulk of this work should happen in a separate repo, in the same manner that @rohennes and I worked on the AsciiDoc and OpenShift AsciiDoc rule sets: https://github.com/rohennes/vale-asciidoc

Once the new rule set is ready for wider adoptation, it can be merged here. WDYT @rolfedh

cc @Chandralekha-RedHat

**Comment by rolfedh** [comment]
I agree. That makes sense.

**Comment by aireilly** [comment]
@Chandralekha-RedHat and I moved this work to https://github.com/reachlekha/vale-localization/tree/main

**Pull request closed without merging**
