### PR TITLE
Display warnings and errors by default, not suggestions #137

### PR DESCRIPTION
**Pull request by rolfedh**
Display warnings and errors by default, not suggestions #137

### CODE REVIEW

**Comment by themr0c** [comment]
I apologize, I didn't meant to close the issue before we reach consensus. I made a typo in a commit.

**Review by themr0c — CHANGES_REQUESTED** [review]
I don't agree to remove suggestions as a default.

Suggestions are meaningful in general. And they are meaningful in the #137 example.

I agree to remove suggestions as a temporary action when onboarding a project, as documented there: https://vale-at-red-hat.github.io/vale-at-red-hat/docs/end-user-guide/defining-a-vale-onboarding-strategy/

Opening specific issues on the rule that you consider misguided would be a far more constructive approach

**Review by michaelryanpeter — COMMENTED** [review]
I find suggestions helpful, as both a reviewer and a writer. 

What if we update the docs with the following:

- How to use use the `--minAlertLevel` flag
- A brief explanation of why suggestions are useful, and a fewcontexts where one might want to turn off suggestions
- Maybe we could have a small shell script to turn off suggestions?

WDYT?

**Comment by themr0c** [comment]
@michaelryanpeter 

> How to use use the --minAlertLevel flag

See: https://redhat-documentation.github.io/vale-at-red-hat/docs/end-user-guide/defining-a-vale-onboarding-strategy/#_focus_on_errors

> A brief explanation of why suggestions are useful, and a fewcontexts where one might want to turn off suggestions

See: https://redhat-documentation.github.io/vale-at-red-hat/docs/end-user-guide/understanding-vale-output/#understanding-vale-alert-levels_docs
and https://redhat-documentation.github.io/vale-at-red-hat/docs/end-user-guide/defining-a-vale-onboarding-strategy/#_focus_on_errors

> Maybe we could have a small shell script to turn off suggestions?

Wouldn't is be more complex than learning to use the --minAlertLevel flag?

**Comment by michaelryanpeter** [comment]
Thank you for pointing these out, @themr0c. I have spent more time in the documentation over the past few weeks. I think that you are right, having writers copy and paste something into their `.bashrc` is probably more complex than learning how to use the flags.

I have an idea for discussion. It is a tangent from @rolfedh's original issue, but it might help. I will open an idea/issue and refer back to here.

**Pull request closed without merging**
