### PR TITLE
Adding unset attribute rule

### PR DESCRIPTION
**Pull request by aireilly**
Adds a new AsciiDoc rule that highlights when an attribute is not unset in the same file. 

The rule fires for an attribute that is not unset in the file.

### CODE REVIEW

**Comment by aireilly** [comment]
This rule does not account for specific ifeval situations. 

```
ifeval::["{context}" == "build-strategies-docker"]
:dockerstrategy:
endif::[]

<module text>

ifeval::["{context}" == "build-strategies-docker"]
:!dockerstrategy:
endif::[]
```

Update the rule to respect ifeval boundaries

**Comment by aireilly** [comment]
> This rule does not account for specific ifeval situations.
> 
> ```
> ifeval::["{context}" == "build-strategies-docker"]
> :dockerstrategy:
> endif::[]
> 
> <module text>
> 
> ifeval::["{context}" == "build-strategies-docker"]
> :!dockerstrategy:
> endif::[]
> ```
> 
> Update the rule to respect ifeval boundaries. For example, how can we validate this? https://github.com/aireilly/openshift-docs/blob/add-symlinks-to-codeowners/modules/cco-ccoctl-configuring.adoc?plain=1

Hacked around this by just counting set and unset attributes

**Comment by aireilly** [comment]
> /cc

What does this mean?

**Comment by aireilly** [comment]
@jeana-redhat Given upcoming tooling changes, I don't think I will be able to spend more time getting this into a better state for AsciiDoc, this will have to do.

**Comment by jeana-redhat** [comment]
> > /cc
> 
> What does this mean?

well, in other repos, it seems to mark you as a reviewer. I was planning to come back around on this :sweat_smile:

**Comment by aireilly** [comment]
Merging this since it's reasonably useful and we're moving off AsciiDoc so why not? :shrug:

**Pull request merged**
