### PR TITLE
Move x86_64 to suggestion

### PR DESCRIPTION
**Pull request by aireilly**
x86_64 should not be flagged as an error. Demoting to suggestion.

### CODE REVIEW

**Comment by aireilly** [comment]
Fixes https://github.com/redhat-documentation/vale-at-red-hat/issues/462

**Comment by rohennes** [comment]
There was also #199 that referenced this question. I was also following that SSG conversation. It seems it is sometimes acceptable.

**Comment by aireilly** [comment]
Ah didn't even know that one was there. Cool, let's get this merged then.

**Review by rohennes — APPROVED** [review]
Can possibly configure a bit more when we see the SSG resolution

**Pull request merged**
