### PR TITLE
issue-641: Add "Rolling Stream" to Vale at Red Hat rules

### PR DESCRIPTION
**Pull request by michellemacrh**
PR addresses issue #641

### CODE REVIEW

**Comment by rohennes** [comment]
Checking on #project-red-hat if plural terms are needed. Might also be worth adding Rolling Application Stream as this seems to be an accepted version of this term according to the SSG.

TBD:
````
rolling stream: Rolling Stream
rolling streams: Rolling Streams
rolling application stream: Rolling Application Stream
rolling application streams: Rolling Application Streams
````

**Comment by michellemacrh** [comment]
@rohennes thanks for seeking that clarification. I've added those updates :)

**Comment by rohennes** [comment]
Thanks so much Michelle! This looks good to me but I'll just wait to see if anybody objects in [Slack](https://redhat-internal.slack.com/archives/C0218RXJK5E/p1696429174365419).

**Review by rohennes — APPROVED** [review]
/lgtm

**Pull request merged**
