### PR TITLE
feat: add Flathub, Flatpak, Podman Desktop

### PR DESCRIPTION
**Pull request by themr0c**
feat: add Flathub, Flatpak, Podman Desktop

### CODE REVIEW

**Comment by michelle-purcell** [comment]
@themr0c - LGTM :+1: 

_**Flatpak Builder**_ is another term related to these exceptions. Would it make sense to add this one also as an exception to both the heading and case-sensitive rules? Thanks.

**Review by michelle-purcell — APPROVED** [review]

**Comment by aireilly** [comment]
LGTM

**Comment by themr0c** [comment]
all flatpak terms deserve probably another pr

**Comment by themr0c** [comment]
@michelle-purcell Flatpak Builder and all Flatpak docs hHeadings in this subsequent pull request: https://github.com/redhat-documentation/vale-at-red-hat/pull/403

**Pull request merged**
