### PR TITLE
No TOC are allowed in OpenShift modules

### LINKED ISSUE #660: No `toc::[]` in modules
See Slack convo: https://redhat-internal.slack.com/archives/C04P5S34GP2/p1696431880071879?thread_ts=1696397420.123719&cid=C04P5S34GP2

In OpenShift, we use `toc::[]` in assemblies only, not modules. If you use in a module it causes build issues.

### PR DESCRIPTION
**Pull request by rohennes**
Fixes #660

### CODE REVIEW

**Comment by aireilly** [comment]
Need to merge the OCP `.vale.ini` update before this?

**Comment by rohennes** [comment]
Yes you're right @aireilly. Do I need to flag this to anyone or can it be pushed through? https://github.com/openshift/openshift-docs/pull/65808

**Comment by aireilly** [comment]
@jeana-redhat should be able to help

**Comment by jeana-redhat** [comment]
@aireilly or @rohennes do I need to wait for this PR to merge before merging https://github.com/openshift/openshift-docs/pull/65808?

**Pull request merged**
