### PR TITLE
Updating reference files to be excluded from vale linting

### PR DESCRIPTION
**Pull request by aireilly**
Adding vale.ini to ignore reference files from the vale linting since they list every error word. This effort is to reduce the spurious Vale linting errors.

### CODE REVIEW

**Comment by themr0c** [comment]
Please don't!

**Comment by themr0c** [comment]
Hum, I apologize, I didn't mean to close it.

I believe this is not a good solution, as 

1. It will impact too many files (all files in the `partials` directory). We should rather limit the scope to the files 
2. It opens the gates to a maintainance nightmare (keeping multiple `vale.ini` files updated).

Prefer the use of scoping: https://docs.errata.ai/vale/scoping#asciidoc

**Comment by aireilly** [comment]
I added the pass directive to the reference files and the python script.
```
pass:[<!-- vale RedHat.CaseSensitiveTerms = NO -->]
pass:[<!-- vale RedHat.TermsErrors = NO -->]
pass:[<!-- vale RedHat.TermsSuggestions = NO -->]
pass:[<!-- vale RedHat.TermsWarnings = NO -->]
pass:[<!-- vale RedHat.Spelling = NO -->]
```

**Comment by aireilly** [comment]
Closing in favour of https://github.com/redhat-documentation/vale-at-red-hat/pull/206

**Pull request closed without merging**
